# Override or modify variables from the `${MACHINE}.conf` machine definition file.

WKS_FILE_beaglebone-yocto ?= "openavr-beaglebone.wks"
WKS_FILE_rpi ?= "openavr-sdcard.wks"

KERNEL_EXTRA_FEATURES_append = " features/overlayfs/overlayfs.scc"

IMAGE_FSTYPES = "squashfs-xz wic wic.bmap"

INITRAMFS_IMAGE = "openavr-image-initramfs"
#INITRAMFS_IMAGE_BUNDLE = "1"
#BOOT_SPACE = "1073741"
#INITRAMFS_MAXSIZE = "315400"
#IMAGE_FSTYPES_pn-${INITRAMFS_IMAGE} = "${INITRAMFS_FSTYPES}"

IMAGE_BOOT_FILES += "\
    ${INITRAMFS_IMAGE}-${MACHINE}.cpio.gz;initramfs.cpio.gz \
    ${IMAGE_BASENAME}-${MACHINE}.squashfs-xz;rootfs.squashfs-xz \
"
